### ISSUE TITLE
where is the DATA folder?

### ISSUE THREAD

**Issue by kingminzhuang** [JakubReha/ProvCTDG#1]
Hi author, I would like to use your framework and your labeled dataset. But I didn't find the darpa dataset

**Comment by JakubReha** [comment]
Hi,
the labeled dataset and the pertained weights are part of releases:

https://github.com/JakubReha/ProvCTDG/releases/tag/v1.0.0.0

**Comment by mik1904** [comment]
Kuba I see that in the readme the link is broken, there is a 'TODO here',
can you please fix this?

Thank you

Michele
